# Probe API
  This is an API to navigate a probe across the map with 5x5 starting from axis 0,0;

# Group Probe
  Resources related to movies in the API.

## Probe get [/get_position]

### Gets a position from the probe [GET]

Gets current coordinate from a probe.

+ Response 200 (application/json)
    [
      {
        x: 0,
        y: 0,
        face: "D"
      }
    ]

## Probe execute [/execute]

### Executes coordinates commands on probe [POST]

Execute single or multiple commands on the probe.

+ Request (application/json)
    [
      {
        "movimentos": ["GE", "M", "M", "M", "GD", "M", "M"]
      }
    ]

+ Response 201 (application/json)
    [
      {
        x: 2,
        y: 3,
        face: "D"
      }
    ]

+ Response 200 (application/json)
    [
      "erro" : Um movimento inválido foi detectado no comando <command> do eixo <axis>, a posição de destino era <position>}."
    ]


## Probe reset [/reset]

### Resets coordinates on the probe [DELETE]

Resets coordinates on the probe.

+ Response 204

